[package]
name = "ido"
version = "0.1.0"
authors = ["Michael Howell <michael@notriddle.com>"]
repository = "https://github.com/notriddle/rust-ido"
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://www.notriddle.com/rustdoc/ido/index.html"

